techincopro/projects/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'projects'
urlpatterns = [
    url(r"^$", views.ProjectList.as_view(), name="project_list"),
    url(r"^sub$", views.subproject_list, name="subproject_list"),
    url(r'^(?P<id>\d+)/(?P<project_id>\d+)$', views.subproject_detail, name='subproject_detail'),
    url(r'^doclist/', views.DocumentListView.as_view(), name='doc_list_'),
    ]
# (?P<slug>[-\w]+)

techincopro/tanks/urls.py
from django.conf.urls import url, include
from django.urls import path
from tanks import views

app_name = 'tanks'
urlpatterns = [
    url(r'^(?P<id>\d+)/$', views.tanks_selected_list, name='tanks_selected_list'),
    url(r'lg/(?P<id>\d+)/$', views.general_welding_list, name='general_welding_list'),
    url(r'gwdetails/(?P<id>\d+)/$', views.general_welding_detail, name='general_welding_detail'),
    url(r'gpdetails/(?P<id>\d+)/$', views.general_part_detail, name='general_part_detail'),
    url(r'generaldetails/(?P<id>\d+)/$', views.general_detail, name='general_detail'),
    url(r'graph/(?P<id>\d+)/$', views.graph_show, name='graph_show'),
    url(r'tankslist/$', views.tanks_list, name='tanks_list'),
    url(r'tanksphoto/(?P<id>\d+)/$', views.tanks_list_photo, name='tanks_photo_list_'),
    url(r'^rtlist/(?P<tank>.+)$', views.RtListView.as_view(), name='rt_list'),
    url(r'^rtlistform/(?P<tank>.+)$', views.RtListViewForm.as_view(), name='rt_list_form'),
    # url(r'rtdetail/(?P<row>\d+)/$', views.rt_details, name='rt_detail_'),
    url(r'rtconfirm/(?P<pk>\d+)/$', views.RtConfirmUpdate.as_view(), name='rt_confirm_'),

    # path('rtlist', views.RtListView.as_view(), name='rt-list'),
    # url(r'^rtlist/(?P<tank>.+)$', views.RtListView.as_view(), name='rt_list'),
    # url(r'^rtlist/', views.people, name='rt_list'),



    ]

techincopro/techincopro/urls.py
from  django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from .views import HomePage,Documents
from filebrowser.sites import site
from django.conf import settings
from controlcenter.views import controlcenter


urlpatterns = [

    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # path('admin/filebrowser/', site.urls),
    # path('admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
    path('projects/', include("projects.urls",namespace="projects")),
    path('tanks/', include("tanks.urls",namespace="tanks")),
    path('', HomePage.as_view(),name="home"),
    # path('tinymce/', include('tinymce.urls')),
    path('operators/', include("operators.urls",namespace="operators")),

    # path('accounts/', include('allauth.urls')),
    # path('admin/dashboard/', controlcenter.urls),



    # path('test/', include('filemanager.urls', namespace='filemanager')),


    # path('filer/', include('filer.urls')),

]
if settings.DEBUG: # will be 'True' in development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techincopro/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Techinco</title>
    <script type="text/javascript" src='{% static 'jquery/dist/jquery.js' %}'></script>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/favicon.png'%}" type="image/x-icon" />

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}"  rel="stylesheet">
    <!-- Animate CSS -->
    <link href="{% static 'vendors/animate/animate.css' %}" rel="stylesheet">
    <!-- Icon CSS-->
	<link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <!-- Camera Slider -->
    <link rel="stylesheet" href="{% static 'vendors/camera-slider/camera.css' %}">
    <!-- Owlcarousel CSS-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/owl_carousel/owl.carousel.css' %}" media="all">

    <!--Theme Styles CSS-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="all" />

    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.min.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <style media="screen">
      .filter-top{
        width: 120px;
      }
    </style>
</head>
<body>
    <!-- Preloader -->
    <div class="preloader"></div>

	<!-- Top Header_Area -->
	<section class="top_header_area">
	    <div class="container">
            <ul class="nav navbar-nav top_nav">
                <li><a href="#"><i class="fa fa-phone"></i>88529728-36</a></li>
                <li><a href="#"><i class="fa fa-envelope-o"></i>info@techinco.net</a></li>
                <li><a href="#"><i class="fa fa-clock-o"></i>Sat - Fri 12:00 - 20:00</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right social_nav">
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
	    </div>
	</section>
	<!-- End Top Header_Area -->





	<!-- Header_Area -->
    <nav class="navbar navbar-default header_aera" id="main_navbar">
        <div class="container">
            <!-- searchForm -->
            <div class="searchForm">
                <form action="#" class="row m0">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        <input type="search" name="search" class="form-control" placeholder="Type & Hit Enter">
                        <span class="input-group-addon form_hide"><i class="fa fa-times"></i></span>
                    </div>
                </form>
            </div><!-- End searchForm -->
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="col-md-2 p0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#min_navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>

                </div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="col-md-10 p0">
                <div class="collapse navbar-collapse" id="min_navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown submenu">
                            <a href="{% url 'projects:project_list'  %}"  >Projects</a>

                        </li>
                        <li class="dropdown submenu">
                            <a href="{% url 'projects:subproject_list'  %}" class="dropdown-toggle" >Subprojects</a>

                        </li>
                        <li class="dropdown submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Modules</a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'tanks:tanks_list'  %}" class="dropdown-toggle" >Tanks</a></li>
                                <li><a href="index-2.html">Piping</a></li>
                                  <li><a href="index-2.html">Equipmen</a></li>
                            </ul>
                        </li>

                        <li><a href="{% url 'projects:doc_list_'   %}">Documents</a></li>
                        <li class="dropdown submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us</a>

                        </li>
                        <li><a href="contact.html">Contact</a></li>
                        <li><a href="#" class="nav_searchFrom"><i class="fa fa-search"></i></a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->


            </div>
        </div><!-- /.container -->
    </nav>
	<!-- End Header_Area -->


  {% block content %}

  {% endblock %}





      <!-- Footer Area -->
      <footer class="footer_area">
          <div class="container">
              <div class="footer_row row">
                  <div class="col-md-3 col-sm-6 footer_about">
                      <h2>TECHINCO’s Vision</h2>

                      <p>Our outlook is to be one of the most competitive and productive service organizations around the world in 2020.</p>
                      <ul class="socail_icon">
                          <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                          <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                          <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                          <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                      </ul>
                  </div>
                  <div class="col-md-3 col-sm-6 footer_about quick">
                      <h2>Quick links</h2>
                      <ul class="quick_link">
                          <li><a href="http://techinco.org/en/Outsourcing"><i class="fa fa-chevron-right"></i>Outsourcing</a></li>
                          <li><a href="http://techinco.org/en/training"><i class="fa fa-chevron-right"></i>Training</a></li>
                          <li><a href="http://techinco.org/en/Commodity"><i class="fa fa-chevron-right"></i>Commodity</a></li>
                          <li><a href="http://techinco.org/en/In-Service"><i class="fa fa-chevron-right"></i>In-Service</a></li>
                          <li><a href="http://techinco.org/en/Material-Inspection"><i class="fa fa-chevron-right"></i>Material Inspection</a></li>
                          <li><a href="http://techinco.org/en/Elevator"><i class="fa fa-chevron-right"></i>Elevator</a></li>
                      </ul>
                  </div>
                  <div class="col-md-3 col-sm-6 footer_about">
                      <h2>Certificates</h2>
                      <a href="#" class="twitter"> Institute Of Standard & Industrial Research Of Iran (I.S.I.R.I.) Inspection Authorization</a>
                      <a href="#" class="twitter">I.S.I.R.I.: Corrosion Control Of Industrial Equipment & Installation.</a>
                      <a href="http://techinco.org/en/certificates" class="twitter">More!</a>
                  </div>
                  <div class="col-md-3 col-sm-6 footer_about">
                      <h2>CONTACT US</h2>
                      <address>
                          <p>Have questions, comments or just want to say hello:</p>
                          <ul class="my_address">
                              <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i>info@techinco.net</a></li>
                              <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i>88529728-36</a></li>
                              <li><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i><span>No.18 , Kooh-e-Noor St.Motahari Ave.Tehran, IRAN</span></a></li>
                          </ul>
                      </address>
                  </div>
              </div>
          </div>
          <div class="copyright_area">
              (c)2018 <a href="http://techinco.org">Techinco</a> All Rights Reserved.
              Designed by <a href="https://colorlib.com">Amir Behvandi</a>
          </div>
      </footer>
      <!-- End Footer Area -->

      <!-- jQuery JS -->
      <script src="{% static 'js/jquery-1.12.0.min.js'%}"></script>
      <!-- Bootstrap JS -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Animate JS -->
      <script src="{% static 'vendors/animate/wow.min.js'%}"></script>
      <!-- Camera Slider -->
      <script src="{% static 'vendors/camera-slider/jquery.easing.1.3.js'%}"></script>
      <script src="{% static 'vendors/camera-slider/camera.min.js'%}"></script>
      <!-- Isotope JS -->
      <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js'%}"></script>
      <script src="{% static 'vendors/isotope/isotope.pkgd.min.js'%}"></script>
      <!-- Progress JS -->
      <script src="{% static 'vendors/Counter-Up/jquery.counterup.min.js'%}"></script>
      <script src="{% static 'vendors/Counter-Up/waypoints.min.js'%}"></script>
      <!-- Owlcarousel JS -->
      <script src="{% static 'vendors/owl_carousel/owl.carousel.min.js'%}"></script>
      <!-- Stellar JS -->
      <script src="{% static 'vendors/stellar/jquery.stellar.js'%}"></script>
      <!-- Theme JS -->
      <script src="{% static 'js/theme.js'%}"></script>
  </body>
  <script language="javascript" type="text/javascript">

  $(document).ready(function(){
      $('.filterable .btn-filter').click(function(){
          var $panel = $(this).parents('.filterable'),
          $filters = $panel.find('.filters input'),
          $tbody = $panel.find('.table tbody');
          if ($filters.prop('disabled') == true) {
              $filters.prop('disabled', false);
              $filters.first().focus();
          } else {
              $filters.val('').prop('disabled', true);
              $tbody.find('.no-result').remove();
              $tbody.find('tr').show();
          }
      });

      $('.filterable .filters input').keyup(function(e){
          /* Ignore tab key */
          var code = e.keyCode || e.which;
          if (code == '9') return;
          /* Useful DOM data and selectors */
          var $input = $(this),
          inputContent = $input.val().toLowerCase(),
          $panel = $input.parents('.filterable'),
          column = $panel.find('.filters th').index($input.parents('th')),
          $table = $panel.find('.table'),
          $rows = $table.find('tbody tr');
          /* Dirtiest filter function ever ;) */
          var $filteredRows = $rows.filter(function(){
              var value = $(this).find('td').eq(column).text().toLowerCase();
              return value.indexOf(inputContent) === -1;
          });
          /* Clean previous no-result if exist */
          $table.find('tbody .no-result').remove();
          /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
          $rows.show();
          $filteredRows.hide();
          /* Prepend no-result row if all rows are filtered */
          if ($filteredRows.length === $rows.length) {
              $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
          }
      });
  });
</script>
  </html>

techincopro/templates/general_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h2>General Details </h2>
        </div>
        <br>
          <div class="row">
            <br>

            <table class="table table-striped table-bordered table-hover">

              <tbody>
                <tr>

                  <td>Row : {{general.row}}</td>
                  <td>DWG No :{{general.DWG_No}} </td>
                </tr>
                <tr>

                  <td>Point Course: {{general.Point_Course}}</td>
                  <td>Point No: {{general.Point_No}}</td>
                </tr>
                <tr>

                  <td>Point Degree :{{general.Point_Degree }} </td>
                  <td>Roundness Before Weld Date : {{general.Roundness_Before_Weld_Date}}</td>

                </tr>
                <tr>

                  <td>Roundness Before Weld No : {{general.Roundness_Before_Weld_No}} </td>
                  <td>Roundness Before Weld Value: {{general.Roundness_Before_Weld_Value}} </td>

                </tr>
              </tbody>
            </table>
            <div class="table-responsive">

</div>


            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}

techincopro/templates/general_part_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h2>General Part Details </h2>
        </div>
        <br>
          <div class="row">
            <br>

            <table class="table table-striped table-bordered table-hover">

              <tbody>
                <tr>

                  <td>Row : {{gp.row}}</td>
                  <td>DWG : {{gp.DWG_No}}</td>
                </tr>
                <tr>

                  <td>Piece Name : {{gp.Piece_Name}}</td>
                  <td>Piece Code 1 : {{gp.Piece_Code1}}</td>
                </tr>
                <tr>

                  <td>Piece No 1 : {{gp.Piece_No1}}</td>
                  <td>Piece Code 2 : {{gp.Piece_Code2}}</td>

                </tr>
                <tr>

                  <td>Material : {{gp.Material}}</td>
                  <td>Head No: {{gp.Head_No}}</td>

                </tr>
              </tbody>
            </table>
            <div class="table-responsive">

</div>


            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}

techincopro/templates/general_welding_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h2>General Welding Details </h2>
        </div>
        <br>
        <img src="{% static 'images/download.svg'%}" alt="" style="width:100%;height:300px">
          <div class="row">
            <br>


            <div class="table-responsive">
  <table class="table table-striped table-bordered table-hover ">
    <tbody>




    <tr>
<td style="font-weight:bold" class="active text-center">Row : <span style="font-weight:normal">{{ gw.row}}</span></td><td style="font-weight:bold" class="active text-center">Tank :<span style="font-weight:normal"> {{ gw.tank}}</span></td>

</tr>
<tr>
  <td style="font-weight:bold" class="active text-center">Location : <span style="font-weight:normal">{{ gw.location}}</span></td><td style="font-weight:bold" class="active text-center">Joint Code 1 :<span style="font-weight:normal"> {{ gw.joint_code_1}}</span></td>

</tr>
<tr>
  <td style="font-weight:bold" class="active text-center">Joint No 1 : <span style="font-weight:normal">{{ gw.joint_no_1}}</span></td><td style="font-weight:bold" class="active text-center">Joint Code : <span style="font-weight:normal">{{ gw.joint_code_2}}</span></td>
  </tr>
<tr>
  <td style="font-weight:bold" class="active text-center">Joint No 2 : <span style="font-weight:normal">{{ gw.joint_no_1}}</span></td><td style="font-weight:bold" class="active text-center">Tickness 1 : <span style="font-weight:normal">{{ gw.thickness_1}}</span></td>

</tr>
<tr>
  <td style="font-weight:bold" class="active text-center">Thickness 2 : <span style="font-weight:normal">{{ gw.thickness_2}}</span></td><td style="font-weight:bold" class="active text-center">Joint Length : <span style="font-weight:normal">{{ gw.joint_lenght}}</span></td>

</tr>
<tr>
  <td style="font-weight:bold" class="active text-center">Material 2 : <span style="font-weight:normal">{{ gw.material_2}}</span></td><td style="font-weight:bold" class="active text-center">WPS No :<span style="font-weight:normal">{{ gw.wps_no}}</span></td></tr>
  <td style="font-weight:bold" class="active text-center">Fitup Date : <span style="font-weight:normal">{{ gw.fitup_date}}</span></td><td style="font-weight:bold" class="active text-center">Fitup No :<span style="font-weight:normal">{{ gw.fitup_no}}</span></td></tr>
  <td style="font-weight:bold" class="active text-center">Welding Date : <span style="font-weight:normal">{{ gw.welding_date}}</span></td><td style="font-weight:bold" class="active text-center">Welding No :<span style="font-weight:normal">{{ gw.welding_no}}</span></td></tr>
  <td style="font-weight:bold" class="active text-center">Welder 1 : <span style="font-weight:normal">{{ gw.welder_1}}</span></td><td style="font-weight:bold" class="active text-center">Welder 2 :<span style="font-weight:normal">{{ gw.welder_2}}</span></td></tr>
  <td style="font-weight:bold" class="active text-center">Welder 3 : <span style="font-weight:normal">{{ gw.welder_3}}</span></td><td style="font-weight:bold" class="active text-center">Welder 4 :<span style="font-weight:normal">{{ gw.welder_4}}</span></td></tr>
  <td style="font-weight:bold" class="active text-center">Welder 3 : <span style="font-weight:normal">{{ gw.welder_3}}</span></td><td style="font-weight:bold" class="active text-center">Welder 4 :<span style="font-weight:normal">{{ gw.welder_4}}</span></td></tr>



</tbody>
  </table>
</div>


            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}

techincopro/templates/graph.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h2>Graph </h2>
        </div>
        <br>
          <div class="row">
            <br>

            <img src="{% static 'images/download.svg'%}" alt="" style="width:100%;height:300px">
          

            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}

techincopro/templates/photo_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h2>Gallery </h2>
        </div>
        <br>
          <div class="row">
            <br>
  {% for obj in tanks_photo %}
            <img src="{{ obj.first_image.url }}" alt="" style="width:100%;height:100px">

{{ obj.first_image.url }}
{%endfor %}
            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}

techincopro/templates/rt_confirm.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

{% load bootstrap %}
<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h1>Do you want to confirm the recored?</h1>
        </div>
        <br>
          <div class="row">
            <br>


          <form method="post">{% csrf_token %}
          {{ form|bootstrap }}
          <input  class="btn btn-warning" type="submit" value="Submit" />
</form>
            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}

techincopro/templates/tanks_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">






  <!-- About Us Area -->
  <section class="about_us_area row">
      <div class="container-fluid">
        <div class="subtittle"><br><br><br><br>
            <h2>Tanks  </h2>
        </div>
          <div class="row">
            <br>

            <div class="table-responsive">
  <table class="table">
<tr>
<td class="warning">Name</td>
<td class="warning">Subproject</td>
<td class="warning">General Welding</td>
<td class="warning">General Part</td>
<td class="warning">General</td>
<td class="warning">UT</td>
<td class="warning">RT</td>
<td class="warning">WPS</td>
<td class="warning">PQR</td>
<td class="warning">Photos</td>
</tr>

    {% for obj in tanks %}

    <tr>
  <td class="active">{{ obj.tank_no }}</td>
  <td class="active">{{ obj.subproject }}</td>
  <td class="active"><a href="{% url 'tanks:general_welding_list' id=obj.id %}" >More!</a></td>
  <td class="active"><a href="{% url 'tanks:general_part_detail' id=obj.id %}" >More!</a></td>
  <td class="active"><a href="{% url 'tanks:general_detail' id=obj.id %}" >More!</a></td>
  <td class="active"><a href="" >More!</a></td>
  <td class="active"><a href="{% url 'tanks:rt_list' tank=obj.tank_no %}" >More!</a></td>
  <td class="active"><a href="" >More!</a></td>
  <td class="active"><a href="" >More!</a></td>
  <td class="active"><a href="{% url 'tanks:tanks_photo_list_' id=obj.id %}" >See</a></td>


</tr>


    {% endfor %}
  </table>
</div>


            <br>
            <br>



          </div>
      </div>
  </section>
  <!-- End About Us Area -->
</div>


{% endblock %}